---
author: Christine Mariskanish
title: CVB3_TT
output:
  html_document:
    toc: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

------------------------------------------------------------------------

```{r, echo = FALSE}

#install.packages("remotes")

#remotes::install_version("SeuratObject", "4.1.4", repos = c("https://satijalab.r-universe.dev", getOption("repos")))
#devtools::install_github("satijalab/seurat", ref = "v4.1.0")
#remotes::install_version("Seurat", "4.4.0", repos = c("https://satijalab.r-universe.dev", getOption("repos")))
#install.packages('clustree')
library(dplyr)
library(patchwork)
library(ggplot2)
library(Seurat)
library(SeuratObject)
library(clustree)
```

## QC CVB3_TT with Seurat {.tabset .tabset-fade .tabset-pills}
```{r}
CVB3_TT.matrix <- Read10X(data.dir = "/Volumes/lvd_qve/Projects/PTD_StrandSpecificCounting_scRNAseq/CellRanger/CVB3_TT/outs/filtered_feature_bc_matrix/")
CVB3_TT <- CreateSeuratObject(counts = CVB3_TT.matrix, project = "CVB3_TT", min.cells = 3, min.features = 10)
CVB3_TT
```


```{r, echo = FALSE}
CVB3_TT.data <- NULL
CVB3_TT.matrix <- NULL
```

### Dataframe
```{r}
str(CVB3_TT)

#Meta.data is the most important field for next steps. It can be acessed using both @ and [[]] operators. Right now it has 3 fields per celL: dataset ID, number of UMI reads detected per cell (nCount_RNA), and the number of expressed (detected) genes per same cell (nFeature_RNA).

meta <- CVB3_TT@meta.data
dim(meta)

head(meta)

summary(meta$nCount_RNA)

summary(meta$nFeature_RNA)
```

### Data plots

```{r, echo = FALSE}
CVB3_TT[["percent.mtribo"]] <- PercentageFeatureSet(CVB3_TT, pattern = "^MT-|^RP[SL]")
CVB3_TT[["percent.mt"]] <- PercentageFeatureSet(CVB3_TT, pattern = "^MT-")

# Add the doublet annotation generated by scrublet (prepare before you start Seurat with scrublet.Rmd)

doublets <- read.table("/Volumes/LVD_QVE/Projects/PTD_StrandSpecificCounting_scRNAseq/CellRanger/CVB3_TT/outs/filtered_feature_bc_matrix/CVB3_TT_Doublet_scores.tsv", header = F)
colnames(doublets) <- c("doublet_scores","predicted_doublets")

CVB3_TT <- AddMetaData(CVB3_TT, metadata = doublets$doublet_scores, col.name = "doublet_scores")
CVB3_TT <- AddMetaData(CVB3_TT, metadata = doublets$predicted_doublets, col.name = "predicted_doublets")
head(CVB3_TT[[]])
#table(CVB3_TT$predicted_doublets)

ggplot(CVB3_TT[[]],aes(x = nCount_RNA)) +
  geom_histogram(bins = 40) + theme_bw() +
  labs(x="Number of UMIs per cell", y = "Number of cells") +
  scale_x_continuous(trans = 'log2')

ggplot(CVB3_TT[[]],aes(x = nFeature_RNA)) +
  geom_histogram(bins = 40) + theme_bw() +
  labs(x="Number of genes per cell", y = "Number of cells") +
  scale_x_continuous(trans = 'log2')

ggplot(CVB3_TT[[]],aes(x = nFeature_RNA, y = nCount_RNA)) +
  geom_point(pch = '.') + theme_bw() +
  labs(x="Number of genes per cell", y = "Number of UMIs per cells") +
  scale_x_continuous(trans = 'log2') +
  scale_y_continuous(trans = 'log2')
VlnPlot(CVB3_TT, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 5, pt.size = 0.1)

plotMT <- ggplot(CVB3_TT@meta.data, aes(nCount_RNA, percent.mtribo)) + geom_point(alpha= 0.7, size = 0.5) + labs(x = 'Total UMI counts per cell', y= 'Percent MT')
plotMT

ggplot(CVB3_TT[[]],aes(x = nCount_RNA, y = percent.mtribo)) +
  geom_point(pch = '.') + theme_bw() +
  labs(x="Number of UMIs per cell", y = "Percent of ribosomal or mitochondrial") +
  scale_x_continuous(trans = 'log2')
```

### Doublet removal

```{r}
CVB3_TT <- subset(CVB3_TT, subset = nCount_RNA > 7000 & nFeature_RNA >2000 & percent.mt < 20)
CVB3_TT <- subset(CVB3_TT, subset = doublet_scores < 0.53)
CVB3_TT
table(CVB3_TT$predicted_doublets)
FeatureScatter(CVB3_TT, feature1 = "nCount_RNA", feature2 = "percent.mt")
FeatureScatter(CVB3_TT, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")

VlnPlot(CVB3_TT, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, pt.size = 0.1) 
```

### Normalize and Find Variable Features

```{r}
CVB3_TT <- NormalizeData(CVB3_TT)
CVB3_TT <- FindVariableFeatures(CVB3_TT, selection.method = "vst", nfeatures = 2000)

# Identify the 10 most highly variable genes
top10 <- head(VariableFeatures(CVB3_TT), 10)

# plot variable features with and without labels
plot1 <- VariableFeaturePlot(CVB3_TT)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
plot1 + plot2
```


```{r}
all.genes <- rownames(CVB3_TT)
CVB3_TT <- ScaleData(CVB3_TT)
```


### Assign Cell-Cycle Scores

For download the files necessary access: https://satijalab.org/seurat/articles/cell_cycle_vignette

```{r, echo = TRUE}
# Read in the expression matrix The first row is a header row, the first column is rownames
exp.mat <- read.table(file = "~/Downloads/cell_cycle_vignette_files/nestorawa_forcellcycle_expressionMatrix.txt", header = TRUE,
    as.is = TRUE, row.names = 1)

# A list of cell cycle markers, from Tirosh et al, 2015, is loaded with Seurat.  We can
# segregate this list into markers of G2/M phase and markers of S phase
s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes
CVB3_TT <- CellCycleScoring(CVB3_TT, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)

# view cell cycle scores and phase assignments
head(CVB3_TT[[]])
# Visualize the distribution of cell cycle markers across
RidgePlot(CVB3_TT, features = c("PCNA", "TOP2A", "MCM6", "MKI67"), ncol = 2)
```


```{r}
# Running a PCA on cell cycle genes reveals, unsurprisingly, that cells separate entirely by
# phase
CVB3_TT <- RunPCA(CVB3_TT, features = c(s.genes, g2m.genes))
PCAPlot(CVB3_TT)
```

```{r}
CVB3_TT <- ScaleData(CVB3_TT, features= all.genes, verbose = T, vars.to.regress = c("S.Score", "G2M.Score"))
```


```{r}
CVB3_TT <- RunPCA(CVB3_TT, verbose = FALSE)

##Evaluate how many dimensions of PCA needed by elbow plot
ElbowPlot(CVB3_TT)
```



```{r}
CVB3_TT <- FindNeighbors(CVB3_TT, dims = 1:20, verbose = FALSE)
CVB_res <- FindClusters(CVB3_TT, resolution = seq(0.1,1, by=0.05))

clustree(CVB_res)

head(CVB_res@meta.data)
head(Idents(CVB_res), 5)

CVB3_res <- RunUMAP(CVB_res, dims = 1:20, verbose = FALSE)
DimPlot(CVB3_res,group.by = 'RNA_snn_res.0.2')
DimPlot(CVB3_res,group.by = 'RNA_snn_res.0.25')
DimPlot(CVB3_res,group.by = 'RNA_snn_res.0.3')
DimPlot(CVB3_res,group.by = 'RNA_snn_res.0.35')
DimPlot(CVB3_res,group.by = 'RNA_snn_res.0.4')
DimPlot(CVB3_res,group.by = 'RNA_snn_res.0.45')
DimPlot(CVB3_res,group.by = 'RNA_snn_res.0.5')
Idents(CVB3_res) <- CVB3_res$RNA_snn_res.0.25
```

```{r}
write.csv(as.data.frame(CVB3_res@reductions$umap@cell.embeddings), file = '/Volumes/lvd_qve/Projects/PTD_StrandSpecificCounting_scRNAseq/CellRanger/CVB3_TT/UMAP.csv')
DimPlot(CVB3_res, label = TRUE)
write.csv(CVB3_res@meta.data, file = '/Volumes/lvd_qve/Projects/CM_kb/CVB3_TT.csv')
```


```{r}

CVB3_TT.markers <- FindAllMarkers(CVB3_res, only.pos = TRUE)

CVB3_TT.markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1)
write.csv(CVB3_TT.markers, file="/Volumes/lvd_qve/Projects/CM_kb/CVB3_TT.markers_Pos.csv")

```

```{r}
CVB3_TT.markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1) %>%
    slice_head(n = 10) %>%
    ungroup() -> top10
DoHeatmap(CVB3_res, features = top10$gene) + NoLegend()
```

```{r}
saveRDS(CVB3_res, file="/Volumes/lvd_qve/Projects/CM_kb/CVB3_TT.rds")
```

```{r}
FeaturePlot(CVB3_res, features = c("ISG15", "OASL", "CCN1", "WFDC1","AKR1C2", "IFIT3", "CRLF1", "AKR1C1", "HIST1H2AE", "IFIT2", "UBE2C", "CD74", "MT1G", "HIST1H4C"))

```
