---
author: Christine Mariskanish
title: "EVA71_TT"
output:
  html_document:
    toc: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

------------------------------------------------------------------------

```{r, echo = FALSE}

#install.packages("remotes")

#remotes::install_version("SeuratObject", "4.1.4", repos = c("https://satijalab.r-universe.dev", getOption("repos")))
#devtools::install_github("satijalab/seurat", ref = "v4.1.0")
#remotes::install_version("Seurat", "4.4.0", repos = c("https://satijalab.r-universe.dev", getOption("repos")))

library(dplyr)
library(patchwork)
library(ggplot2)
library(Seurat)
library(SeuratObject)
library(clustree)
```

## QC EVA71_TT with Seurat {.tabset .tabset-fade .tabset-pills}
```{r}
EVA71_TT.matrix <- Read10X(data.dir = "/Volumes/lvd_qve/Projects/PTD_StrandSpecificCounting_scRNAseq/CellRanger/EVA71_TT/outs/filtered_feature_bc_matrix/")
EVA71_TT <- CreateSeuratObject(counts = EVA71_TT.matrix, project = "EVA71_TT", min.cells = 3, min.features = 10)
EVA71_TT
```


```{r, echo = FALSE}
EVA71_TT.data <- NULL
EVA71_TT.matrix <- NULL
```

### Dataframe
```{r}
str(EVA71_TT)

meta <- EVA71_TT@meta.data
dim(meta)

head(meta)

summary(meta$nCount_RNA)

summary(meta$nFeature_RNA)
```

### Data plots

```{r, echo = FALSE}
EVA71_TT[["percent.mtribo"]] <- PercentageFeatureSet(EVA71_TT, pattern = "^MT-|^RP[SL]")
EVA71_TT[["percent.mt"]] <- PercentageFeatureSet(EVA71_TT, pattern = "^MT-")
# Let's add the doublet annotation generated by scrublet (prepare before you start Seurat with scrublet.Rmd)

doublets <- read.table("/Volumes/lvd_qve/Projects/PTD_StrandSpecificCounting_scRNAseq/CellRanger/EVA71_TT/outs/filtered_feature_bc_matrix/EVA71_TT_Doublet_scores.tsv", header = F)
colnames(doublets) <- c("doublet_scores","predicted_doublets")

EVA71_TT <- AddMetaData(EVA71_TT, metadata = doublets$doublet_scores, col.name = "doublet_scores")
EVA71_TT <- AddMetaData(EVA71_TT, metadata = doublets$predicted_doublets, col.name = "predicted_doublets")
head(EVA71_TT[[]])
#table(EVA71_TT$predicted_doublets)

ggplot(EVA71_TT[[]],aes(x = nCount_RNA)) +
  geom_histogram(bins = 40) + theme_bw() +
  labs(x="Number of UMIs per cell", y = "Number of cells") +
  scale_x_continuous(trans = 'log2')

ggplot(EVA71_TT[[]],aes(x = nFeature_RNA)) +
  geom_histogram(bins = 40) + theme_bw() +
  labs(x="Number of genes per cell", y = "Number of cells") +
  scale_x_continuous(trans = 'log2')

ggplot(EVA71_TT[[]],aes(x = nFeature_RNA, y = nCount_RNA)) +
  geom_point(pch = '.') + theme_bw() +
  labs(x="Number of genes per cell", y = "Number of UMIs per cells") +
  scale_x_continuous(trans = 'log2') +
  scale_y_continuous(trans = 'log2')
VlnPlot(EVA71_TT, features = c("nFeature_RNA", "nCount_RNA", "percent.mtribo", "percent.mt"), ncol = 5, pt.size = 0.1)

plotMT <- ggplot(EVA71_TT@meta.data, aes(nCount_RNA, percent.mtribo)) + geom_point(alpha= 0.7, size = 0.5) + labs(x = 'Total UMI counts per cell', y= 'Percent MT')
plotMT

ggplot(EVA71_TT[[]],aes(x = nCount_RNA, y = percent.mtribo)) +
  geom_point(pch = '.') + theme_bw() +
  labs(x="Number of UMIs per cell", y = "Percent of ribosomal or mitochondrial") +
  scale_x_continuous(trans = 'log2')
```

### Doublet removal

```{r}
EVA71_TT <- subset(EVA71_TT, subset = nCount_RNA > 5000 & nFeature_RNA >2000 & percent.mt < 20 & percent.mtribo < 40 & percent.mtribo >15)
EVA71_TT <- subset(EVA71_TT, subset = doublet_scores < 0.58)
EVA71_TT
table(EVA71_TT$predicted_doublets)
FeatureScatter(EVA71_TT, feature1 = "nCount_RNA", feature2 = "percent.mt")
FeatureScatter(EVA71_TT, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")

VlnPlot(EVA71_TT, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, pt.size = 0.1) 
```

### Normalize and Find Variable Features

```{r}
EVA71_TT <- NormalizeData(EVA71_TT)
EVA71_TT <- FindVariableFeatures(EVA71_TT, selection.method = "vst", nfeatures = 2000)

# Identify the 10 most highly variable genes
top10 <- head(VariableFeatures(EVA71_TT), 10)

# plot variable features with and without labels
plot1 <- VariableFeaturePlot(EVA71_TT)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
plot1 + plot2

```


```{r}
all.genes <- rownames(EVA71_TT)
EVA71_TT <- ScaleData(EVA71_TT)
```


### Assign Cell-Cycle Scores

For download the files necessary access: https://satijalab.org/seurat/articles/cell_cycle_vignette

```{r, echo = TRUE}
# Read in the expression matrix The first row is a header row, the first column is rownames
exp.mat <- read.table(file = "~/Downloads/cell_cycle_vignette_files/nestorawa_forcellcycle_expressionMatrix.txt", header = TRUE,
    as.is = TRUE, row.names = 1)

# A list of cell cycle markers, from Tirosh et al, 2015, is loaded with Seurat.  We can
# segregate this list into markers of G2/M phase and markers of S phase
s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes
EVA71_TT <- CellCycleScoring(EVA71_TT, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)

# view cell cycle scores and phase assignments
head(EVA71_TT[[]])
# Visualize the distribution of cell cycle markers across
RidgePlot(EVA71_TT, features = c("PCNA", "TOP2A", "MCM6", "MKI67"), ncol = 2)
```


```{r}
# Running a PCA on cell cycle genes reveals, unsurprisingly, that cells separate entirely by
# phase
EVA71_TT <- RunPCA(EVA71_TT, features = c(s.genes, g2m.genes))
PCAPlot(EVA71_TT)
Idents(EVA71_TT) <- EVA71_TT$orig.ident
head(Idents(EVA71_TT))
PCAPlot(EVA71_TT)
```

```{r}
EVA71_TT <- ScaleData(EVA71_TT, features= all.genes, verbose = T, vars.to.regress = c("S.Score", "G2M.Score"))
```


```{r}
EVA71_TT <- RunPCA(EVA71_TT, verbose = FALSE)

##Evaluate how many dimensions of PCA needed by elbow plot
ElbowPlot(EVA71_TT)
```



```{r}
EVA71_TT <- FindNeighbors(EVA71_TT, dims = 1:20, verbose = FALSE)
EVA71_TT <- FindClusters(EVA71_TT, verbose = FALSE, resolution = seq(.1,1, by= 0.05))
head(EVA71_TT@meta.data)
head(Idents(EVA71_TT), 5)
clustree(EVA71_TT)

EVA71_TT <- RunUMAP(EVA71_TT, dims = 1:20, verbose = FALSE)
DimPlot(EVA71_TT,group.by = 'RNA_snn_res.0.1')
DimPlot(EVA71_TT,group.by = 'RNA_snn_res.0.15')
DimPlot(EVA71_TT,group.by = 'RNA_snn_res.0.2')
DimPlot(EVA71_TT,group.by = 'RNA_snn_res.0.25')
DimPlot(EVA71_TT,group.by = 'RNA_snn_res.0.3')
DimPlot(EVA71_TT,group.by = 'RNA_snn_res.0.35')
DimPlot(EVA71_TT,group.by = 'RNA_snn_res.0.4')
DimPlot(EVA71_TT,group.by = 'RNA_snn_res.0.45')
DimPlot(EVA71_TT,group.by = 'RNA_snn_res.0.5')
Idents(EVA71_TT) <- EVA71_TT$RNA_snn_res.0.15

```

```{r}
write.csv(as.data.frame(EVA71_TT@reductions$umap@cell.embeddings), file = '/Volumes/lvd_qve/Projects/PTD_StrandSpecificCounting_scRNAseq/CellRanger/EVA71_TT/UMAP.csv')
DimPlot(EVA71_TT, label = TRUE)
write.csv(EVA71_TT@meta.data, file = '/Volumes/lvd_qve/Projects/CM_kb/EVA71_TT.csv')
```


```{r}

EVA71_TT.markers <- FindAllMarkers(EVA71_TT, only.pos = TRUE)

EVA71_TT.markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1)
write.csv(EVA71_TT.markers, file="/Volumes/lvd_qve/Projects/CM_kb/EVA71_TT.markersPos.csv")

```

```{r}
EVA71_TT.markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1) %>%
    slice_head(n = 10) %>%
    ungroup() -> top10
DoHeatmap(EVA71_TT, features = top10$gene) + NoLegend()
```

```{r}
saveRDS(EVA71_TT, file="/Volumes/lvd_qve/Projects/CM_kb/EVA71TT.rds")
```

```{r}
#cluster0markers <- FindMarkers(EVA71_TT, ident.1 = 0, logfc.threshold = 0.25, test.use = "roc", only.pos = TRUE)
FeaturePlot(EVA71_TT, features = c("ISG15", "OASL", "CCN1", "WFDC1","AKR1C2", "IFIT3", "CRLF1", "AKR1C1", "HIST1H2AE", "IFIT2", "UBE2C", "CD74", "MT1G", "HIST1H4C"))
head(EVA71_TT@meta.data)
head(Idents(EVA71_TT), 5)
```
